<a href="https://colab.research.google.com/github/ONOSPETER/Exercism/blob/main/IFS208_Assgn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<b>IFS208</b>- Data Science<br/>
<i>Assignment using Dataset CP1 from chapter 3</i>

<h3>OBIEGBA ONOTEOGHENE PETER </h3>
<b>IFS/23/6801</b>

In [3]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [4]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [6]:
data = pd.read_csv("./SP1.csv", na_values=":")
data

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,BbMx>2.5,BbAv>2.5,BbMx<2.5,BbAv<2.5,BbAH,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA
0,SP1,18/08/12,Celta,Malaga,0,1,A,0,0,D,...,2.12,2.02,1.83,1.78,21,-0.25,1.99,1.96,1.98,1.91
1,SP1,18/08/12,Mallorca,Espanol,2,1,H,1,1,D,...,2.30,2.17,1.72,1.68,20,-0.50,2.01,1.98,1.95,1.90
2,SP1,18/08/12,Sevilla,Getafe,2,1,H,2,0,H,...,2.04,1.96,1.92,1.84,23,-0.75,1.90,1.82,2.12,2.05
3,SP1,19/08/12,Ath Bilbao,Betis,3,5,A,0,3,A,...,2.00,1.88,2.00,1.92,18,-0.75,2.18,2.12,1.81,1.76
4,SP1,19/08/12,Barcelona,Sociedad,5,1,H,4,1,H,...,1.33,1.30,3.65,3.36,23,-2.75,1.98,1.93,1.99,1.93
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,SP1,01/06/13,Mallorca,Valladolid,4,2,H,2,1,H,...,1.74,1.67,2.28,2.17,26,-1.00,1.96,1.89,2.02,1.97
376,SP1,01/06/13,Real Madrid,Osasuna,4,2,H,2,0,H,...,1.33,1.24,4.00,3.74,25,-1.50,1.71,1.68,2.33,2.24
377,SP1,01/06/13,Sevilla,Valencia,4,3,H,2,1,H,...,1.62,1.50,2.75,2.48,23,0.50,1.76,1.72,2.25,2.18
378,SP1,01/06/13,Vallecano,Ath Bilbao,2,2,D,1,1,D,...,1.62,1.55,2.60,2.35,23,-0.25,1.90,1.83,2.13,2.05
379,SP1,01/06/13,Zaragoza,Ath Madrid,1,3,A,0,0,D,...,1.98,1.83,2.10,1.98,23,-0.50,2.32,2.23,1.72,1.69

In [7]:
data.head()

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,BbMx>2.5,BbAv>2.5,BbMx<2.5,BbAv<2.5,BbAH,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA
0,SP1,18/08/12,Celta,Malaga,0,1,A,0,0,D,...,2.12,2.02,1.83,1.78,21,-0.25,1.99,1.96,1.98,1.91
1,SP1,18/08/12,Mallorca,Espanol,2,1,H,1,1,D,...,2.30,2.17,1.72,1.68,20,-0.50,2.01,1.98,1.95,1.90
2,SP1,18/08/12,Sevilla,Getafe,2,1,H,2,0,H,...,2.04,1.96,1.92,1.84,23,-0.75,1.90,1.82,2.12,2.05
3,SP1,19/08/12,Ath Bilbao,Betis,3,5,A,0,3,A,...,2.00,1.88,2.00,1.92,18,-0.75,2.18,2.12,1.81,1.76
4,SP1,19/08/12,Barcelona,Sociedad,5,1,H,4,1,H,...,1.33,1.30,3.65,3.36,23,-2.75,1.98,1.93,1.99,1.93

In [ ]:
data.tail()

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,BbMx>2.5,BbAv>2.5,BbMx<2.5,BbAv<2.5,BbAH,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA
375,SP1,01/06/13,Mallorca,Valladolid,4,2,H,2,1,H,...,1.74,1.67,2.28,2.17,26,-1.00,1.96,1.89,2.02,1.97
376,SP1,01/06/13,Real Madrid,Osasuna,4,2,H,2,0,H,...,1.33,1.24,4.00,3.74,25,-1.50,1.71,1.68,2.33,2.24
377,SP1,01/06/13,Sevilla,Valencia,4,3,H,2,1,H,...,1.62,1.50,2.75,2.48,23,0.50,1.76,1.72,2.25,2.18
378,SP1,01/06/13,Vallecano,Ath Bilbao,2,2,D,1,1,D,...,1.62,1.55,2.60,2.35,23,-0.25,1.90,1.83,2.13,2.05
379,SP1,01/06/13,Zaragoza,Ath Madrid,1,3,A,0,0,D,...,1.98,1.83,2.10,1.98,23,-0.50,2.32,2.23,1.72,1.69

In [8]:
data[:50]

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,BbMx>2.5,BbAv>2.5,BbMx<2.5,BbAv<2.5,BbAH,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA
0,SP1,18/08/12,Celta,Malaga,0,1,A,0,0,D,...,2.12,2.02,1.83,1.78,21,-0.25,1.99,1.96,1.98,1.91
1,SP1,18/08/12,Mallorca,Espanol,2,1,H,1,1,D,...,2.30,2.17,1.72,1.68,20,-0.50,2.01,1.98,1.95,1.90
2,SP1,18/08/12,Sevilla,Getafe,2,1,H,2,0,H,...,2.04,1.96,1.92,1.84,23,-0.75,1.90,1.82,2.12,2.05
3,SP1,19/08/12,Ath Bilbao,Betis,3,5,A,0,3,A,...,2.00,1.88,2.00,1.92,18,-0.75,2.18,2.12,1.81,1.76
4,SP1,19/08/12,Barcelona,Sociedad,5,1,H,4,1,H,...,1.33,1.30,3.65,3.36,23,-2.75,1.98,1.93,1.99,1.93
5,SP1,19/08/12,Levante,Ath Madrid,1,1,D,1,1,D,...,2.06,1.97,1.90,1.84,21,0.25,2.00,1.93,1.98,1.93
6,SP1,19/08/12,Real Madrid,Valencia,1,1,D,1,1,D,...,1.46,1.40,3.00,2.79,23,-1.75,1.97,1.93,2.01,1.93
7,SP1,20/08/12,La Coruna,Osasuna,2,0,H,0,0,D,...,2.26,2.12,1.75,1.71,21,-0.25,1.80,1.75,2.25,2.13
8,SP1,20/08/12,Vallecano,Granada,1,0,H,0,0,D,...,2.04,1.93,1.99,1.87,19,-0.25,1.96,1.92,1.99,1.94
9,SP1,20/08/12,Zaragoza,Valladolid,0,1,A,0,1,A,...,2.10,1.99,1.88,1.82,19,0.00,1.59,1.55,2.58,2.47
10,SP1,25/08/12,Betis,Vallecano,1,2,A,1,1,D,...,1.97,1.89,2.06,1.91,20,-0.75,1.94,1.91,2.00,1.97
11,SP1,25/08/12,Espanol,Zaragoza,1,2,A,1,0,H,...,2.18,2.09,1.80,1.73,19,-0.75,1.93,1.90,2.01,1.98
12,SP1,25/08/12,Malaga,Mallorca,1,1,D,0,0,D,...,2.12,2.04,1.85,1.77,18,-0.50,1.96,1.92,2.00,1.96
13,SP1,25/08/12,Sociedad,Celta,2,1,H,0,0,D,...,2.25,2.10,1.79,1.72,18,-0.25,1.83,1.79,2.16,2.10
14,SP1,26/08/12,Getafe,Real Madrid,2,1,H,0,1,A,...,1.56,1.50,2.70,2.52,18,1.50,2.02,1.93,1.98,1.95
15,SP1,26/08/12,Granada,Sevilla,1,1,D,1,1,D,...,2.17,2.05,1.85,1.76,20,0.25,1.82,1.78,2.16,2.11
16,SP1,26/08/12,Osasuna,Barcelona,1,2,A,1,0,H,...,1.55,1.49,2.70,2.52,18,1.75,2.05,2.01,1.91,1.88
17,SP1,26/08/12,Valencia,La Coruna,3,3,D,3,1,H,...,1.87,1.79,2.10,2.00,21,-1.00,1.81,1.77,2.17,2.12
18,SP1,27/08/12,Ath Madrid,Ath Bilbao,4,0,H,2,0,H,...,1.85,1.77,2.12,2.04,19,-0.75,1.83,1.80,2.15,2.10
19,SP1,27/08/12,Valladolid,Levante,2,0,H,1,0,H,...,2.26,2.18,1.75,1.68,17,-0.25,1.85,1.81,2.13,2.08
20,SP1,01/09/12,Celta,Osasuna,2,0,H,0,0,D,...,2.20,2.11,1.78,1.72,23,-0.25,1.82,1.79,2.16,2.10
21,SP1,01/09/12,La Coruna,Getafe,1,1,D,1,1,D,...,2.18,2.06,1.82,1.76,24,-0.25,1.92,1.88,2.05,1.99
22,SP1,01/09/12,Mallorca,Sociedad,1,0,H,0,0,D,...,2.33,2.19,1.75,1.66,20,-0.50,2.14,2.10,1.83,1.79
23,SP1,01/09/12,Zaragoza,Malaga,0,1,A,0,0,D,...,2.28,2.17,1.76,1.68,24,0.00,2.05,1.98,1.91,1.87
24,SP1,02/09/12,Ath Bilbao,Valladolid,2,0,H,0,0,D,...,2.00,1.94,1.95,1.87,21,-0.50,2.10,2.05,1.87,1.83
25,SP1,02/09/12,Barcelona,Valencia,1,0,H,1,0,H,...,1.44,1.36,3.12,2.98,21,-1.75,1.80,1.77,2.19,2.12
26,SP1,02/09/12,Levante,Espanol,3,2,H,0,2,A,...,2.40,2.24,1.72,1.63,24,-0.25,1.97,1.93,1.99,1.94
27,SP1,02/09/12,Real Madrid,Granada,3,0,H,1,0,H,...,1.29,1.24,4.35,3.84,23,-2.75,2.03,1.99,1.92,1.88
28,SP1,02/09/12,Vallecano,Sevilla,0,0,D,0,0,D,...,2.10,2.02,1.88,1.79,24,0.00,2.08,2.03,1.88,1.83
29,SP1,15/09/12,Getafe,Barcelona,1,4,A,0,1,A,...,1.61,1.52,2.64,2.45,24,1.50,1.98,1.94,1.99,1.93
30,SP1,15/09/12,Malaga,Levante,3,1,H,1,0,H,...,2.18,2.04,1.80,1.77,24,-0.75,2.00,1.94,2.02,1.93
31,SP1,15/09/12,Sevilla,Real Madrid,1,0,H,1,0,H,...,1.63,1.54,2.64,2.40,23,0.75,2.16,2.10,1.84,1.79
32,SP1,15/09/12,Valencia,Celta,2,1,H,1,1,D,...,1.73,1.65,2.34,2.21,23,-1.00,1.83,1.79,2.16,2.10
33,SP1,16/09/12,Ath Madrid,Vallecano,4,3,H,1,0,H,...,1.67,1.58,2.52,2.31,21,-1.50,1.99,1.96,1.96,1.92
34,SP1,16/09/12,Espanol,Ath Bilbao,3,3,D,2,0,H,...,1.98,1.90,1.97,1.90,24,-0.25,1.99,1.93,1.98,1.93
35,SP1,16/09/12,Granada,La Coruna,1,1,D,0,1,A,...,2.34,2.21,1.70,1.65,22,-0.25,2.00,1.94,2.01,1.93
36,SP1,16/09/12,Osasuna,Mallorca,1,1,D,0,0,D,...,2.34,2.20,1.72,1.65,24,-0.25,2.03,1.98,1.93,1.89
37,SP1,16/09/12,Sociedad,Zaragoza,2,0,H,0,0,D,...,2.12,2.04,1.84,1.77,20,-0.50,1.86,1.82,2.12,2.07
38,SP1,17/09/12,Valladolid,Betis,0,1,A,0,0,D,...,2.11,2.03,1.85,1.77,22,-0.25,1.84,1.80,2.14,2.08
39,SP1,22/09/12,Barcelona,Granada,2,0,H,0,0,D,...,1.25,1.22,4.40,3.98,23,-2.75,1.95,1.89,2.03,1.98
40,SP1,22/09/12,Betis,Espanol,1,0,H,1,0,H,...,2.01,1.90,1.97,1.90,20,-0.50,1.96,1.93,1.99,1.95
41,SP1,22/09/12,Celta,Getafe,2,1,H,0,0,D,...,2.20,2.06,1.80,1.75,20,-0.50,2.05,2.01,1.89,1.87
42,SP1,22/09/12,Zaragoza,Osasuna,3,1,H,2,1,H,...,2.43,2.28,1.71,1.62,23,-0.25,1.96,1.91,2.01,1.96
43,SP1,23/09/12,Ath Bilbao,Malaga,0,0,D,0,0,D,...,1.95,1.87,2.04,1.92,21,-0.25,2.06,1.97,1.94,1.90
44,SP1,23/09/12,Ath Madrid,Valladolid,2,1,H,2,0,H,...,1.65,1.58,2.44,2.31,22,-1.50,2.04,1.97,1.95,1.90
45,SP1,23/09/12,Levante,Sociedad,2,1,H,0,1,A,...,2.30,2.18,1.75,1.68,20,-0.25,1.98,1.93,1.97,1.93
46,SP1,23/09/12,Mallorca,Valencia,2,0,H,1,0,H,...,2.16,2.07,1.82,1.75,22,0.00,2.12,2.02,1.91,1.84
47,SP1,24/09/12,La Coruna,Sevilla,0,2,A,0,0,D,...,2.11,2.03,1.85,1.78,21,0.00,1.93,1.89,2.01,1.95
48,SP1,24/09/12,Vallecano,Real Madrid,0,2,A,0,1,A,...,1.55,1.49,2.70,2.53,22,1.50,2.08,2.04,1.89,1.84
49,SP1,26/09/12,Betis,Ath Madrid,2,4,A,2,1,H,...,1.94,1.85,2.04,1.95,24,0.25,1.95,1.91,1.99,1.96

In [9]:
data[data["HomeTeam"] == "Barcelona"]

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,BbMx>2.5,BbAv>2.5,BbMx<2.5,BbAv<2.5,BbAH,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA
4,SP1,19/08/12,Barcelona,Sociedad,5,1,H,4,1,H,...,1.33,1.30,3.65,3.36,23,-2.75,1.98,1.93,1.99,1.93
25,SP1,02/09/12,Barcelona,Valencia,1,0,H,1,0,H,...,1.44,1.36,3.12,2.98,21,-1.75,1.80,1.77,2.19,2.12
39,SP1,22/09/12,Barcelona,Granada,2,0,H,0,0,D,...,1.25,1.22,4.40,3.98,23,-2.75,1.95,1.89,2.03,1.98
67,SP1,07/10/12,Barcelona,Real Madrid,2,2,D,1,1,D,...,1.57,1.51,2.74,2.50,22,-0.75,2.17,2.11,1.81,1.78
90,SP1,03/11/12,Barcelona,Celta,3,1,H,2,1,H,...,1.27,1.24,4.15,3.84,22,-2.50,1.82,1.77,2.20,2.12
110,SP1,17/11/12,Barcelona,Zaragoza,3,1,H,2,1,H,...,1.25,1.21,4.40,4.15,22,-2.75,1.86,1.83,2.11,2.04
131,SP1,01/12/12,Barcelona,Ath Bilbao,5,1,H,3,0,H,...,1.26,1.22,4.60,4.01,25,-2.75,2.05,2.00,1.91,1.86
154,SP1,16/12/12,Barcelona,Ath Madrid,4,1,H,2,1,H,...,1.47,1.41,3.20,2.78,25,-1.50,1.90,1.84,2.09,2.02
175,SP1,06/01/13,Barcelona,Espanol,4,0,H,4,0,H,...,1.29,1.24,4.35,3.88,23,-2.75,1.96,1.91,1.99,1.94
205,SP1,27/01/13,Barcelona,Osasuna,5,1,H,3,1,H,...,1.30,1.25,4.35,3.81,21,-2.50,1.82,1.77,2.25,2.10
226,SP1,10/02/13,Barcelona,Getafe,6,1,H,2,0,H,...,1.26,1.21,4.60,4.19,23,-2.50,1.77,1.71,2.29,2.19
241,SP1,23/02/13,Barcelona,Sevilla,2,1,H,0,1,A,...,1.33,1.26,4.00,3.59,25,-2.00,1.89,1.84,2.08,2.02
261,SP1,09/03/13,Barcelona,La Coruna,2,0,H,1,0,H,...,1.30,1.25,4.10,3.72,23,-2.50,2.08,1.99,1.93,1.88
275,SP1,17/03/13,Barcelona,Vallecano,3,1,H,2,0,H,...,1.29,1.23,4.50,3.93,24,-2.50,1.88,1.82,2.14,2.05
291,SP1,06/04/13,Barcelona,Mallorca,5,0,H,4,0,H,...,1.40,1.34,3.45,3.06,25,-2.00,2.01,1.95,1.99,1.92
311,SP1,20/04/13,Barcelona,Levante,1,0,H,0,0,D,...,1.46,1.39,3.00,2.84,23,-2.00,2.00,1.96,1.98,1.91
335,SP1,05/05/13,Barcelona,Betis,4,2,H,1,2,A,...,1.41,1.35,3.40,3.07,26,-2.00,2.10,2.03,1.91,1.85
355,SP1,19/05/13,Barcelona,Valladolid,2,1,H,2,0,H,...,1.40,1.34,3.40,3.12,25,-1.75,2.03,1.97,1.94,1.90
370,SP1,01/06/13,Barcelona,Malaga,4,1,H,3,0,H,...,1.35,1.28,3.75,3.48,26,-1.50,1.78,1.73,2.22,2.16

<i>Here I am filtering all the columns for a particular team</i>

In [29]:
Team = input("Input the Team: ")
data[(data["HomeTeam"] == Team) | (data["AwayTeam"] == Team)]

Input the Team: Betis

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,BbAv>2.5,BbMx<2.5,BbAv<2.5,BbAH,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA,FTHG - FTAG
3,SP1,19/08/12,Ath Bilbao,Betis,3,5,A,0,3,A,...,1.88,2.00,1.92,18,-0.75,2.18,2.12,1.81,1.76,2
10,SP1,25/08/12,Betis,Vallecano,1,2,A,1,1,D,...,1.89,2.06,1.91,20,-0.75,1.94,1.91,2.00,1.97,1
38,SP1,17/09/12,Valladolid,Betis,0,1,A,0,0,D,...,2.03,1.85,1.77,22,-0.25,1.84,1.80,2.14,2.08,1
40,SP1,22/09/12,Betis,Espanol,1,0,H,1,0,H,...,1.90,1.97,1.90,20,-0.50,1.96,1.93,1.99,1.95,1
49,SP1,26/09/12,Betis,Ath Madrid,2,4,A,2,1,H,...,1.85,2.04,1.95,24,0.25,1.95,1.91,1.99,1.96,2
50,SP1,29/09/12,Malaga,Betis,4,0,H,2,0,H,...,1.91,1.97,1.89,24,-0.75,1.98,1.90,2.02,1.96,4
61,SP1,06/10/12,Betis,Sociedad,2,0,H,1,0,H,...,1.94,1.93,1.86,20,-0.50,2.08,2.02,1.89,1.86,2
77,SP1,21/10/12,Osasuna,Betis,0,0,D,0,0,D,...,2.10,1.83,1.74,18,-0.50,2.08,2.04,1.89,1.84,0
80,SP1,27/10/12,Betis,Valencia,1,0,H,1,0,H,...,1.87,2.01,1.94,21,0.00,2.11,2.06,1.85,1.80,1
99,SP1,05/11/12,Getafe,Betis,2,4,A,0,0,D,...,1.91,1.98,1.89,18,-0.25,1.76,1.73,2.29,2.17,2
100,SP1,09/11/12,Betis,Granada,1,2,A,0,1,A,...,1.95,1.94,1.85,21,-0.75,2.03,1.97,1.97,1.90,1
118,SP1,18/11/12,Sevilla,Betis,5,1,H,4,0,H,...,1.78,2.11,2.02,23,-0.75,1.97,1.92,1.99,1.94,4
121,SP1,24/11/12,Betis,Real Madrid,1,0,H,1,0,H,...,1.41,3.10,2.76,24,1.50,2.19,2.12,1.85,1.77,1
137,SP1,02/12/12,La Coruna,Betis,2,3,A,0,1,A,...,1.87,2.02,1.93,25,-0.25,1.96,1.86,2.09,2.00,1
147,SP1,09/12/12,Betis,Barcelona,1,2,A,1,2,A,...,1.41,3.00,2.77,23,1.50,2.06,2.00,1.92,1.86,1
158,SP1,17/12/12,Celta,Betis,0,1,A,0,0,D,...,1.91,1.96,1.88,22,-0.25,1.81,1.72,2.27,2.18,1
166,SP1,22/12/12,Betis,Mallorca,1,2,A,1,1,D,...,1.94,1.92,1.86,23,-0.75,2.04,1.95,1.96,1.90,1
170,SP1,04/01/13,Zaragoza,Betis,1,2,A,0,1,A,...,2.11,1.80,1.72,23,0.00,1.67,1.63,2.43,2.32,1
186,SP1,13/01/13,Betis,Levante,2,0,H,1,0,H,...,2.04,1.84,1.76,22,-0.25,1.72,1.68,2.35,2.24,2
199,SP1,21/01/13,Betis,Ath Bilbao,1,1,D,1,1,D,...,1.80,2.10,2.00,21,-0.50,1.95,1.91,2.02,1.96,0
208,SP1,27/01/13,Vallecano,Betis,3,0,H,1,0,H,...,1.87,2.10,1.92,21,-0.25,2.03,1.94,1.98,1.92,3
215,SP1,03/02/13,Ath Madrid,Betis,1,0,H,0,0,D,...,1.72,2.24,2.11,23,-1.00,1.88,1.81,2.10,2.04,1
229,SP1,11/02/13,Betis,Valladolid,0,0,D,0,0,D,...,2.07,1.83,1.75,22,-0.50,1.94,1.88,2.04,1.98,0
235,SP1,17/02/13,Espanol,Betis,1,0,H,1,0,H,...,2.07,1.80,1.74,20,-0.50,2.20,2.06,1.88,1.82,1
246,SP1,24/02/13,Betis,Malaga,3,0,H,3,0,H,...,2.08,1.82,1.74,22,0.00,1.89,1.84,2.07,2.02,3
258,SP1,03/03/13,Sociedad,Betis,3,3,D,0,1,A,...,1.89,2.00,1.90,22,-0.75,2.20,2.02,1.91,1.86,0
260,SP1,08/03/13,Betis,Osasuna,2,1,H,1,0,H,...,2.14,1.78,1.70,21,-0.50,1.91,1.87,2.08,2.02,1
274,SP1,16/03/13,Valencia,Betis,3,0,H,1,0,H,...,1.76,2.18,2.05,24,-1.00,2.21,2.15,1.83,1.74,3
289,SP1,01/04/13,Betis,Getafe,0,0,D,0,0,D,...,2.02,1.89,1.79,20,-0.75,2.18,2.12,1.82,1.77,0
290,SP1,05/04/13,Granada,Betis,1,5,A,0,3,A,...,2.07,1.81,1.76,23,-0.25,2.02,1.97,1.96,1.91,4
300,SP1,12/04/13,Betis,Sevilla,3,3,D,1,3,A,...,1.82,2.12,2.00,24,-0.25,2.25,2.18,1.79,1.74,0
313,SP1,20/04/13,Real Madrid,Betis,3,1,H,1,0,H,...,1.38,3.10,2.91,23,-1.50,1.80,1.75,2.19,2.14,2
329,SP1,29/04/13,Betis,La Coruna,1,1,D,0,1,A,...,1.69,2.28,2.15,22,-0.75,2.27,2.22,1.75,1.70,0
335,SP1,05/05/13,Barcelona,Betis,4,2,H,1,2,A,...,1.35,3.40,3.07,26,-2.00,2.10,2.03,1.91,1.85,2
348,SP1,12/05/13,Betis,Celta,1,0,H,0,0,D,...,1.76,2.18,2.05,25,-0.75,2.19,2.13,1.81,1.75,1
359,SP1,20/05/13,Mallorca,Betis,1,0,H,1,0,H,...,1.75,2.19,2.07,22,0.00,1.92,1.87,2.04,1.98,1
362,SP1,26/05/13,Betis,Zaragoza,4,0,H,2,0,H,...,1.75,2.22,2.06,22,-0.75,2.37,2.30,1.69,1.65,4
374,SP1,01/06/13,Levante,Betis,1,1,D,0,0,D,...,1.70,2.25,2.13,24,0.25,2.02,1.97,1.94,1.90,0

<i>Filtering all the game played by 2 teams</i>

In [40]:
HTeam = input("Input the Home Team: ")
ATeam = input("Input the Away Team: ")
data[((data["HomeTeam"] == HTeam) & (data["AwayTeam"] == ATeam)) | ((data["HomeTeam"] == ATeam) & (data["AwayTeam"] == HTeam))]

Input the Home Team: Barcelona
Input the Away Team: Osasuna

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,BbAv>2.5,BbMx<2.5,BbAv<2.5,BbAH,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA,FTHG - FTAG
16,SP1,26/08/12,Osasuna,Barcelona,1,2,A,1,0,H,...,1.49,2.70,2.52,18,1.75,2.05,2.01,1.91,1.88,1
205,SP1,27/01/13,Barcelona,Osasuna,5,1,H,3,1,H,...,1.25,4.35,3.81,21,-2.50,1.82,1.77,2.25,2.10,4

Adding a new row "FHTG - FTAG" to the data

In [18]:
data["FTHG - FTAG"] = data["FTHG"] - data["FTAG"]
data.head()

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,BbAv>2.5,BbMx<2.5,BbAv<2.5,BbAH,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA,FTHG - FTAG
0,SP1,18/08/12,Celta,Malaga,0,1,A,0,0,D,...,2.02,1.83,1.78,21,-0.25,1.99,1.96,1.98,1.91,-1
1,SP1,18/08/12,Mallorca,Espanol,2,1,H,1,1,D,...,2.17,1.72,1.68,20,-0.50,2.01,1.98,1.95,1.90,1
2,SP1,18/08/12,Sevilla,Getafe,2,1,H,2,0,H,...,1.96,1.92,1.84,23,-0.75,1.90,1.82,2.12,2.05,1
3,SP1,19/08/12,Ath Bilbao,Betis,3,5,A,0,3,A,...,1.88,2.00,1.92,18,-0.75,2.18,2.12,1.81,1.76,-2
4,SP1,19/08/12,Barcelona,Sociedad,5,1,H,4,1,H,...,1.30,3.65,3.36,23,-2.75,1.98,1.93,1.99,1.93,4

Making sure row "FHTG - FTAG" is only positive

In [23]:
data["FTHG - FTAG"] = data["FTHG - FTAG"].abs()
data[:50]

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,BbAv>2.5,BbMx<2.5,BbAv<2.5,BbAH,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA,FTHG - FTAG
0,SP1,18/08/12,Celta,Malaga,0,1,A,0,0,D,...,2.02,1.83,1.78,21,-0.25,1.99,1.96,1.98,1.91,1
1,SP1,18/08/12,Mallorca,Espanol,2,1,H,1,1,D,...,2.17,1.72,1.68,20,-0.50,2.01,1.98,1.95,1.90,1
2,SP1,18/08/12,Sevilla,Getafe,2,1,H,2,0,H,...,1.96,1.92,1.84,23,-0.75,1.90,1.82,2.12,2.05,1
3,SP1,19/08/12,Ath Bilbao,Betis,3,5,A,0,3,A,...,1.88,2.00,1.92,18,-0.75,2.18,2.12,1.81,1.76,2
4,SP1,19/08/12,Barcelona,Sociedad,5,1,H,4,1,H,...,1.30,3.65,3.36,23,-2.75,1.98,1.93,1.99,1.93,4
5,SP1,19/08/12,Levante,Ath Madrid,1,1,D,1,1,D,...,1.97,1.90,1.84,21,0.25,2.00,1.93,1.98,1.93,0
6,SP1,19/08/12,Real Madrid,Valencia,1,1,D,1,1,D,...,1.40,3.00,2.79,23,-1.75,1.97,1.93,2.01,1.93,0
7,SP1,20/08/12,La Coruna,Osasuna,2,0,H,0,0,D,...,2.12,1.75,1.71,21,-0.25,1.80,1.75,2.25,2.13,2
8,SP1,20/08/12,Vallecano,Granada,1,0,H,0,0,D,...,1.93,1.99,1.87,19,-0.25,1.96,1.92,1.99,1.94,1
9,SP1,20/08/12,Zaragoza,Valladolid,0,1,A,0,1,A,...,1.99,1.88,1.82,19,0.00,1.59,1.55,2.58,2.47,1
10,SP1,25/08/12,Betis,Vallecano,1,2,A,1,1,D,...,1.89,2.06,1.91,20,-0.75,1.94,1.91,2.00,1.97,1
11,SP1,25/08/12,Espanol,Zaragoza,1,2,A,1,0,H,...,2.09,1.80,1.73,19,-0.75,1.93,1.90,2.01,1.98,1
12,SP1,25/08/12,Malaga,Mallorca,1,1,D,0,0,D,...,2.04,1.85,1.77,18,-0.50,1.96,1.92,2.00,1.96,0
13,SP1,25/08/12,Sociedad,Celta,2,1,H,0,0,D,...,2.10,1.79,1.72,18,-0.25,1.83,1.79,2.16,2.10,1
14,SP1,26/08/12,Getafe,Real Madrid,2,1,H,0,1,A,...,1.50,2.70,2.52,18,1.50,2.02,1.93,1.98,1.95,1
15,SP1,26/08/12,Granada,Sevilla,1,1,D,1,1,D,...,2.05,1.85,1.76,20,0.25,1.82,1.78,2.16,2.11,0
16,SP1,26/08/12,Osasuna,Barcelona,1,2,A,1,0,H,...,1.49,2.70,2.52,18,1.75,2.05,2.01,1.91,1.88,1
17,SP1,26/08/12,Valencia,La Coruna,3,3,D,3,1,H,...,1.79,2.10,2.00,21,-1.00,1.81,1.77,2.17,2.12,0
18,SP1,27/08/12,Ath Madrid,Ath Bilbao,4,0,H,2,0,H,...,1.77,2.12,2.04,19,-0.75,1.83,1.80,2.15,2.10,4
19,SP1,27/08/12,Valladolid,Levante,2,0,H,1,0,H,...,2.18,1.75,1.68,17,-0.25,1.85,1.81,2.13,2.08,2
20,SP1,01/09/12,Celta,Osasuna,2,0,H,0,0,D,...,2.11,1.78,1.72,23,-0.25,1.82,1.79,2.16,2.10,2
21,SP1,01/09/12,La Coruna,Getafe,1,1,D,1,1,D,...,2.06,1.82,1.76,24,-0.25,1.92,1.88,2.05,1.99,0
22,SP1,01/09/12,Mallorca,Sociedad,1,0,H,0,0,D,...,2.19,1.75,1.66,20,-0.50,2.14,2.10,1.83,1.79,1
23,SP1,01/09/12,Zaragoza,Malaga,0,1,A,0,0,D,...,2.17,1.76,1.68,24,0.00,2.05,1.98,1.91,1.87,1
24,SP1,02/09/12,Ath Bilbao,Valladolid,2,0,H,0,0,D,...,1.94,1.95,1.87,21,-0.50,2.10,2.05,1.87,1.83,2
25,SP1,02/09/12,Barcelona,Valencia,1,0,H,1,0,H,...,1.36,3.12,2.98,21,-1.75,1.80,1.77,2.19,2.12,1
26,SP1,02/09/12,Levante,Espanol,3,2,H,0,2,A,...,2.24,1.72,1.63,24,-0.25,1.97,1.93,1.99,1.94,1
27,SP1,02/09/12,Real Madrid,Granada,3,0,H,1,0,H,...,1.24,4.35,3.84,23,-2.75,2.03,1.99,1.92,1.88,3
28,SP1,02/09/12,Vallecano,Sevilla,0,0,D,0,0,D,...,2.02,1.88,1.79,24,0.00,2.08,2.03,1.88,1.83,0
29,SP1,15/09/12,Getafe,Barcelona,1,4,A,0,1,A,...,1.52,2.64,2.45,24,1.50,1.98,1.94,1.99,1.93,3
30,SP1,15/09/12,Malaga,Levante,3,1,H,1,0,H,...,2.04,1.80,1.77,24,-0.75,2.00,1.94,2.02,1.93,2
31,SP1,15/09/12,Sevilla,Real Madrid,1,0,H,1,0,H,...,1.54,2.64,2.40,23,0.75,2.16,2.10,1.84,1.79,1
32,SP1,15/09/12,Valencia,Celta,2,1,H,1,1,D,...,1.65,2.34,2.21,23,-1.00,1.83,1.79,2.16,2.10,1
33,SP1,16/09/12,Ath Madrid,Vallecano,4,3,H,1,0,H,...,1.58,2.52,2.31,21,-1.50,1.99,1.96,1.96,1.92,1
34,SP1,16/09/12,Espanol,Ath Bilbao,3,3,D,2,0,H,...,1.90,1.97,1.90,24,-0.25,1.99,1.93,1.98,1.93,0
35,SP1,16/09/12,Granada,La Coruna,1,1,D,0,1,A,...,2.21,1.70,1.65,22,-0.25,2.00,1.94,2.01,1.93,0
36,SP1,16/09/12,Osasuna,Mallorca,1,1,D,0,0,D,...,2.20,1.72,1.65,24,-0.25,2.03,1.98,1.93,1.89,0
37,SP1,16/09/12,Sociedad,Zaragoza,2,0,H,0,0,D,...,2.04,1.84,1.77,20,-0.50,1.86,1.82,2.12,2.07,2
38,SP1,17/09/12,Valladolid,Betis,0,1,A,0,0,D,...,2.03,1.85,1.77,22,-0.25,1.84,1.80,2.14,2.08,1
39,SP1,22/09/12,Barcelona,Granada,2,0,H,0,0,D,...,1.22,4.40,3.98,23,-2.75,1.95,1.89,2.03,1.98,2
40,SP1,22/09/12,Betis,Espanol,1,0,H,1,0,H,...,1.90,1.97,1.90,20,-0.50,1.96,1.93,1.99,1.95,1
41,SP1,22/09/12,Celta,Getafe,2,1,H,0,0,D,...,2.06,1.80,1.75,20,-0.50,2.05,2.01,1.89,1.87,1
42,SP1,22/09/12,Zaragoza,Osasuna,3,1,H,2,1,H,...,2.28,1.71,1.62,23,-0.25,1.96,1.91,2.01,1.96,2
43,SP1,23/09/12,Ath Bilbao,Malaga,0,0,D,0,0,D,...,1.87,2.04,1.92,21,-0.25,2.06,1.97,1.94,1.90,0
44,SP1,23/09/12,Ath Madrid,Valladolid,2,1,H,2,0,H,...,1.58,2.44,2.31,22,-1.50,2.04,1.97,1.95,1.90,1
45,SP1,23/09/12,Levante,Sociedad,2,1,H,0,1,A,...,2.18,1.75,1.68,20,-0.25,1.98,1.93,1.97,1.93,1
46,SP1,23/09/12,Mallorca,Valencia,2,0,H,1,0,H,...,2.07,1.82,1.75,22,0.00,2.12,2.02,1.91,1.84,2
47,SP1,24/09/12,La Coruna,Sevilla,0,2,A,0,0,D,...,2.03,1.85,1.78,21,0.00,1.93,1.89,2.01,1.95,2
48,SP1,24/09/12,Vallecano,Real Madrid,0,2,A,0,1,A,...,1.49,2.70,2.53,22,1.50,2.08,2.04,1.89,1.84,2
49,SP1,26/09/12,Betis,Ath Madrid,2,4,A,2,1,H,...,1.85,2.04,1.95,24,0.25,1.95,1.91,1.99,1.96,2

Taking the mean of column "FTHG - FTAG"

In [27]:
mean_fthg_ftag = data["FTHG - FTAG"].mean()
print(f"The mean of the column [FTHG - FTAG] is: {mean_fthg_ftag}")

The mean of the column [FTHG - FTAG] is: 1.4289473684210525

In [38]:
code = input("Input any Code(A, D, H): ")
Count = data[data["FTR"] == code].shape[0]
print(f"There are {Count} matches with {code} FTR code")

Input any Code(A, D, H): H
There are 189 matches with H FTR code

In [39]:
code = input("Input any Code(A, D, H): ")
Count = data[data["HTR"] == code].shape[0]
print(f"There are {Count} matches with {code} HTR code")

Input any Code(A, D, H): H
There are 146 matches with H HTR code